import {
  GENERATIONS_TYPES,
  QUICK_SUBSCRIPTION_BUTTONS,
  SMART_SUBSCRIPTION_BUTTONS,
} from './subscription';

export enum PACKAGES {
  smart = 'smart',
  quick = 'quick',
}

export const SMART_PRODUCTS = {
  [SMART_SUBSCRIPTION_BUTTONS.smart_15]: {
    id: SMART_SUBSCRIPTION_BUTTONS.smart_15,
    count: 15,
    price: 7900,
    type: GENERATIONS_TYPES.smartWizard,
    titleT: 'subscription.products.smart.title',
    descriptionT: 'subscription.products.smart.description',
    command: SMART_SUBSCRIPTION_BUTTONS.smart_15,
    currency: 'UAH',
    name: 'Smart',
    package: PACKAGES.smart,
    image: 'https://textonika.s3.eu-west-1.amazonaws.com/products/smart15.jpg',
  },
  [SMART_SUBSCRIPTION_BUTTONS.smart_50]: {
    id: SMART_SUBSCRIPTION_BUTTONS.smart_50,
    count: 50,
    price: 19900,
    type: GENERATIONS_TYPES.smartWizard,
    titleT: 'subscription.products.smart.title',
    descriptionT: 'subscription.products.smart.description',
    command: SMART_SUBSCRIPTION_BUTTONS.smart_50,
    currency: 'UAH',
    name: 'Smart',
    package: PACKAGES.smart,
    image: 'https://textonika.s3.eu-west-1.amazonaws.com/products/smart50.jpg',
  },
  [SMART_SUBSCRIPTION_BUTTONS.smart_120]: {
    id: SMART_SUBSCRIPTION_BUTTONS.smart_120,
    count: 120,
    price: 39900,
    type: GENERATIONS_TYPES.smartWizard,
    titleT: 'subscription.products.smart.title',
    descriptionT: 'subscription.products.smart.description',
    command: SMART_SUBSCRIPTION_BUTTONS.smart_120,
    currency: 'UAH',
    name: 'Smart',
    package: PACKAGES.smart,
    image: 'https://textonika.s3.eu-west-1.amazonaws.com/products/smart120.jpg',
  },
};

export const QUICK_PRODUCTS = {
  [QUICK_SUBSCRIPTION_BUTTONS.quick_30]: {
    id: QUICK_SUBSCRIPTION_BUTTONS.quick_30,
    count: 30,
    price: 10900,
    type: GENERATIONS_TYPES.quickWizard,
    titleT: 'subscription.products.smart.title',
    descriptionT: 'subscription.products.smart.description',
    command: QUICK_SUBSCRIPTION_BUTTONS.quick_30,
    currency: 'UAH',
    name: 'Quick',
    package: PACKAGES.quick,
    image: 'https://textonika.s3.eu-west-1.amazonaws.com/products/quick30.jpg',
  },
  [QUICK_SUBSCRIPTION_BUTTONS.quick_50]: {
    id: QUICK_SUBSCRIPTION_BUTTONS.quick_50,
    count: 50,
    price: 14900,
    type: GENERATIONS_TYPES.quickWizard,
    titleT: 'subscription.products.smart.title',
    descriptionT: 'subscription.products.smart.description',
    command: QUICK_SUBSCRIPTION_BUTTONS.quick_50,
    currency: 'UAH',
    name: 'Quick',
    package: PACKAGES.quick,
    image: 'https://textonika.s3.eu-west-1.amazonaws.com/products/quick50.jpg',
  },
  [QUICK_SUBSCRIPTION_BUTTONS.quick_100]: {
    id: QUICK_SUBSCRIPTION_BUTTONS.quick_100,
    count: 100,
    price: 23900,
    type: GENERATIONS_TYPES.quickWizard,
    titleT: 'subscription.products.smart.title',
    descriptionT: 'subscription.products.smart.description',
    command: QUICK_SUBSCRIPTION_BUTTONS.quick_100,
    currency: 'UAH',
    name: 'Quick',
    package: PACKAGES.quick,
    image: 'https://textonika.s3.eu-west-1.amazonaws.com/products/quick100.jpg',
  },
};
